# for log level setting
logging:
  level:
    org.springframework.web: DEBUG

# for datasource setting
spring:
  h2:
    console:
      enabled: true
      path: /h2-console # localhost:8080/h2-console
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/test  # H2 접속 정보
    username: sa
    password: 1111

# for OAS setting
# ref : https://springdoc.org/v2/#getting-started
# when hosting : http://localhost:8080/swagger-ui/index.html
springdoc:
  packages-to-scan: com.anservice.core
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    operations-sorter: alpha
    tags-sorter: alpha
    enabled: true
    display-query-params-without-oauth2: true