# for log level setting
logging:
  level:
    org.springframework.web: DEBUG

# for datasource setting
spring:
  h2:
    console:
      enabled: true
      path: /h2-console # localhost:8080/h2-console
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/test  # H2 접속 정보
    username: sa
    password: 1111